spring:
  application:
    name: lecture
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hhplus
    username: testuser
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # H2 대신 PostgreSQLDialect로 변경

logging:
  level:
    root: INFO
    com:
      hhplus:
        lecture: DEBUG
